all:
  children:
    app_servers:
      hosts:
        portfolio-server:
          ansible_host: 10.10.20.100
          ansible_user: onesto
          ansible_ssh_private_key_file: ~/.ssh/id_rsa

    db_servers:
      hosts:
        mongo-server:
          ansible_host: 10.10.30.101
          ansible_user: onesto
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
