name: Deploy to Server via API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Llamar a /deploy en tu servidor
        run: |
          curl -X POST https://${{ secrets.SERVER_HOST }}/deploy \
          -H "Authorization: Bearer ${{ secrets.DEPLOY_SECRET }}"
